### ISSUE TITLE
Continuous IMU data

### ISSUE THREAD

**Issue by PranavShevkar** [riegllms/ros-riegl-vz#1]
I am using the Riegl ROS2 package with ROS2 Humble. I would like to access the raw IMU and compass readings from the Riegl scanner similar to the GNSS data. Is there any possibility of accessing this from the scanner?

**Comment by riegl-af** [comment]
Currently the driver does not support reading raw IMU data from the scanner. However, it would be possible and I'm putting it on my to-do list.

**Comment by PranavShevkar** [comment]
Thankyou so much.
